api:
  name: "s-bbdd-api"
  port: "8083"
  
dynamoDB:
  AccessKey: ASIA6HRQW4O7HCK3WV5Z
  SecretKey: VbTKjJHTsOGBypCWfCaaczVUeSRY7IOTSSG0Yv5s
  token: FwoGZXIvYXdzEAkaDGQzOmmiRhPEDfIjZSLHARy1cAInA0ixAsA1YeQ2WuGg23UC+FIpgslW9/ePk2s9m8W7j2lYbi5zVTqC7zOSWLMH65AH7yYaCim+zPWUzhUcrHEWLilCf6WvVcVqCMHFK4waUNmYFfKjJks9yX5O4N7QTB+jbExZJqgGA8739tFtDVWlac0nyJMlPvW/zUNGNaXb7YgMpCLjVuQSaU/k+DJXvhqOzwPAlfi7pyZNxz7KcUTdwf2GVNpSu85RyKwbG/Gj0L34JEhFL6U4qOX82WsnpFTIY8worPC3qwYyLdYvMaBCJS8PcCBb5VJh8LL8ekVKqZ2l97/clYuKXL+JKN17QBo+SXQq5NaF7Q==
  
  
  
  
  