api:
  name: "s-bbdd-api"
  port: "8085"
  
dynamoDB:
  AccessKey: ASIA6HRQW4O7LHJX2ZGZ
  SecretKey: j5S1Cv/dRPAjPGTcdcQpTYvA6FvcbTtioOLmMj7x
  token: FwoGZXIvYXdzEDMaDNejg/lt3UVQQ23qbyLHAcFEk2SzSzbNtrrNHVJ2c6LTws/IdEgCeJlmWJ8Pbh03DfZ8EiuLmoult+6KjTkfjJN/1XvetPgyCOAFsrp+ZCdj0gJYLygGrXDYrTJOOGCi+rbPFEh/rmbh9fm2UxyCCaqxyQ2yhtjELPvZKfd3jTAQTNaA+IefDAUcUUBKWKDSqTOKjwxQssPwDOPRvvgtcpANi0KpvGedWsoiDusTaWLWFf52rxjqeVuQ9GqexenXpld2fYzAmaxIjur13Ap2wkK+qShC+IUok/TAqwYyLTsGHxMEeXogcz/b1YzP8mNSJ9Sw0Kn/mepPd1sTrPILXws45IoHf2xJCI2lcA==
  
  
  
  